/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var path = __toESM(require("path"));
var MyPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.eventRefs = [];
  }
  async onload() {
    this.addCommand({
      id: "export-censored-document",
      name: "Export Censored Document",
      checkCallback: (checking) => {
        const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (markdownView) {
          if (!checking) {
            this.main();
          }
          return true;
        }
      }
    });
  }
  async main() {
    const html = await this.MarkdownToHTML();
    const alteredDocument = await this.buildHTMLDocument(html);
    const currentPath = this.getCurrentFilePath();
    const dir = currentPath ? path.dirname(currentPath) : "";
    const filePath = `${dir}/${this.getCurrentFileName()}.html`;
    await this.SaveFile(alteredDocument, filePath);
    await this.app.openWithDefaultApp(filePath);
    await this.deleteFile(filePath);
  }
  async deleteFile(filePath) {
    const normalizedPath = (0, import_obsidian.normalizePath)(filePath);
    const exists = await this.app.vault.adapter.exists(normalizedPath);
    if (!exists) {
      new import_obsidian.Notice("FAILED TO DELETE HTML FILE");
      throw new Error("FAILED TO DELETE HTML FILE");
    }
    await new Promise((r) => setTimeout(r, 3e3));
    await this.app.vault.adapter.remove(normalizedPath);
  }
  async MarkdownToHTML() {
    let inputFile = this.getCurrentFilePath();
    if (!inputFile) {
      new import_obsidian.Notice("Could not determine the file path.");
      throw new Error("Could not determine the file path.");
    }
    let outputFile = this.replaceFileExtension(inputFile, "html");
    let exists = await this.app.vault.adapter.exists(
      (0, import_obsidian.normalizePath)(outputFile)
    );
    if (exists) {
      new import_obsidian.Notice("NOTE: Overwriting Existing HTML file");
      await this.app.vault.adapter.remove((0, import_obsidian.normalizePath)(outputFile));
    }
    this.app.commands.executeCommandById(
      "obsidian-pandoc:pandoc-export-html"
    );
    const waitForFile = async (timeoutMs, intervalMs) => {
      const startTime = Date.now();
      while (Date.now() - startTime < timeoutMs) {
        const exists2 = await this.app.vault.adapter.exists(
          (0, import_obsidian.normalizePath)(outputFile)
        );
        if (exists2)
          return;
        await new Promise((r) => setTimeout(r, intervalMs));
      }
      throw new Error("Timed out waiting for HTML export");
    };
    try {
      await waitForFile(6e4, 200);
    } catch (err) {
      if (err instanceof Error) {
        new import_obsidian.Notice(err.message);
      }
      throw err;
    }
    const file = await this.app.vault.adapter.read(
      (0, import_obsidian.normalizePath)(outputFile)
    );
    await this.app.vault.adapter.remove((0, import_obsidian.normalizePath)(outputFile));
    return file;
  }
  async buildHTMLDocument(html) {
    const customHead = `
			<link rel="preconnect" href="https://fonts.googleapis.com">
			<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
			<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
		`;
    const cssPath = path.join(this.manifest.dir, "src", "page.css");
    const customCss = await this.app.vault.adapter.read(
      (0, import_obsidian.normalizePath)(cssPath)
    );
    const scriptPath = path.join(this.manifest.dir, "src", "page.js");
    const customScript = await this.app.vault.adapter.read(
      (0, import_obsidian.normalizePath)(scriptPath)
    );
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, "text/html");
    const newHead = doc.createElement("head");
    const title = doc.createElement("title");
    const style = doc.createElement("style");
    const script = doc.createElement("script");
    title.textContent = "Censored Docuemnt";
    style.textContent = customCss;
    script.textContent = customScript;
    newHead.appendChild(title);
    newHead.appendChild(style);
    newHead.appendChild(script);
    const headFragment = parser.parseFromString(
      `<head>${customHead}</head>`,
      "text/html"
    );
    [...headFragment.head.childNodes].forEach((node) => {
      newHead.appendChild(node);
    });
    const oldHead = doc.querySelector("head");
    if (oldHead && oldHead.parentNode) {
      oldHead.parentNode.replaceChild(newHead, oldHead);
    }
    const newHtml = "<!DOCTYPE html>\n" + doc.documentElement.outerHTML;
    return newHtml;
  }
  async SaveFile(content, filePath) {
    const existingFile = this.app.vault.getAbstractFileByPath(filePath);
    if (existingFile instanceof import_obsidian.TFile) {
      await this.app.vault.modify(existingFile, content);
    } else {
      await this.app.vault.create(filePath, content);
    }
    new import_obsidian.Notice("HTML File Saved");
  }
  replaceFileExtension(file, ext) {
    let pos = file.lastIndexOf(".");
    return file.slice(0, pos < 0 ? file.length : pos) + "." + ext;
  }
  getCurrentFilePath() {
    const fileData = this.app.workspace.getActiveFile();
    if (!fileData)
      return null;
    return fileData.path;
  }
  getCurrentFileName() {
    var _a;
    let inputFile = this.getCurrentFilePath();
    if (!inputFile) {
      new import_obsidian.Notice("Could not determine the file path.");
      throw new Error("Could not determine the file path.");
    }
    const fileName = (_a = inputFile.split(/[/\\]/).pop()) != null ? _a : "";
    const dotIndex = fileName.lastIndexOf(".");
    return dotIndex !== -1 ? fileName.substring(0, dotIndex) : fileName;
  }
  onunload() {
    super.onunload();
    for (const eventRef of this.eventRefs) {
      this.app.workspace.offref(eventRef);
    }
  }
};
